name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - feat/ci-cd

jobs:
  build:
    name: 'Build for ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: compactify-linux
            bin_name: compactify
            archive_name: compactify-linux.tar.gz
          - os: macos-latest
            artifact_name: compactify-macos
            bin_name: compactify
            archive_name: compactify-macos.tar.gz
          - os: windows-latest
            artifact_name: compactify-windows
            bin_name: compactify.exe
            archive_name: compactify-windows.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache: true
      
      - name: Install libvips (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev

      - name: Install libvips (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install vips
      
      - name: Install libvips (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          update: true
          install: >-
            mingw-w64-x86_64-libvips
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            zip
      
      - name: Build and Archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          CGO_ENABLED=1 go build -ldflags="-w -s" -trimpath -o ${{ matrix.bin_name }} .
          
          # Injeta o README para Mac e Linux
          cat << 'EOF' > README.txt
          Compactify CLI
          ==============
          Command-line tool for image optimization using libvips.

          Basic Usage:
            ./${{ matrix.bin_name }} -h

          Recommended Installation:
            Move this executable to your PATH (e.g., /usr/local/bin/) to access it from anywhere.
          EOF
          
          tar -czvf ${{ matrix.archive_name }} ${{ matrix.bin_name }} README.txt

      - name: Build and Archive (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig"
          mkdir release_pkg
          go version
          CGO_ENABLED=1 go build -ldflags="-w -s" -trimpath -o release_pkg/${{ matrix.bin_name }} .
          ldd release_pkg/${{ matrix.bin_name }} | grep "mingw64" | awk '{print $3}' | xargs -I '{}' cp '{}' release_pkg/
          
          # Injeta o README salva-vidas para o Windows
          cat << 'EOF' > release_pkg/README.txt
          Compactify CLI
          ==============
          IMPORTANT: This is a command-line tool. DO NOT double-click the .exe file.

          Instalation Instructions:
          1. Extract the entire folder (with all .dll files) to a safe location.
             Example: C:\Program Files\Compactify\
          2. Add this path (C:\Program Files\Compactify\) to the 'Path' environment variable in Windows.
          3. Open a new terminal (PowerShell or CMD).
          4. Type the command below to see the available commands:
             compactify -h
          EOF

          cd release_pkg && zip -r ../${{ matrix.archive_name }} * && cd ..
      
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.archive_name }}
  
  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Create Github Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}